version: '3'

services:
  neura-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - ollama
    environment:
      - NODE_ENV=production
      - OLLAMA_HOST=http://ollama:11434
    restart: unless-stopped
    networks:
      - neura-network
    volumes:
      - ./prisma:/app/prisma
      - ./data:/app/data
    
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    restart: unless-stopped
    volumes:
      - ollama-data:/root/.ollama
    networks:
      - neura-network
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - neura-app
    restart: unless-stopped
    networks:
      - neura-network

volumes:
  ollama-data:
    driver: local

networks:
  neura-network:
    driver: bridge 